// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7eUQ5BQN73QvXC0N_kAn_Z6wmUT46nDg',
    appId: '1:217763982735:web:a2a45126ea1712eddbeffa',
    messagingSenderId: '217763982735',
    projectId: 'xmanah',
    authDomain: 'xmanah.firebaseapp.com',
    databaseURL: 'https://xmanah-default-rtdb.firebaseio.com',
    storageBucket: 'xmanah.firebasestorage.app',
    measurementId: 'G-0Y6DP9NDNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP_fKj_36oygPMufDeB-L0_aK10qvxyBE',
    appId: '1:217763982735:android:3449c877a190daaedbeffa',
    messagingSenderId: '217763982735',
    projectId: 'xmanah',
    databaseURL: 'https://xmanah-default-rtdb.firebaseio.com',
    storageBucket: 'xmanah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC51BjSQJd5WB_46LObDTVwF_6xwkHYR_U',
    appId: '1:217763982735:ios:986d01b3d1465728dbeffa',
    messagingSenderId: '217763982735',
    projectId: 'xmanah',
    databaseURL: 'https://xmanah-default-rtdb.firebaseio.com',
    storageBucket: 'xmanah.firebasestorage.app',
    iosBundleId: 'com.example.xmanah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC51BjSQJd5WB_46LObDTVwF_6xwkHYR_U',
    appId: '1:217763982735:ios:986d01b3d1465728dbeffa',
    messagingSenderId: '217763982735',
    projectId: 'xmanah',
    databaseURL: 'https://xmanah-default-rtdb.firebaseio.com',
    storageBucket: 'xmanah.firebasestorage.app',
    iosBundleId: 'com.example.xmanah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7eUQ5BQN73QvXC0N_kAn_Z6wmUT46nDg',
    appId: '1:217763982735:web:6a0266b4c9a3c76fdbeffa',
    messagingSenderId: '217763982735',
    projectId: 'xmanah',
    authDomain: 'xmanah.firebaseapp.com',
    databaseURL: 'https://xmanah-default-rtdb.firebaseio.com',
    storageBucket: 'xmanah.firebasestorage.app',
    measurementId: 'G-WVTHDHDPC0',
  );
}
